# Generated by Django 4.0.6 on 2022-08-08 05:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vjusers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_private', models.BooleanField()),
                ('session_name', models.CharField(max_length=50)),
                ('session_description', models.CharField(max_length=200)),
                ('session_password', models.CharField(max_length=256)),
                ('session_location', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('connection_range', models.IntegerField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by', to='vjusers.user')),
                ('host_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='host_id', to='vjusers.user')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_by', to='vjusers.user')),
            ],
        ),
    ]
