# Generated by Django 4.0.6 on 2022-08-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vjsessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_password',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
