# Generated by Django 4.0.6 on 2022-08-13 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vjusers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='can_host',
        ),
    ]
