C AREA OF A TRIANGLE - HERON'S FORMULA
C INPUT - CARD READER UNIT 5, INTEGER INPUT, NO BLANK CARD FOR END OF DATA
C OUTPUT - LINE PRINTER UNIT 6, REAL OUTPUT
C INPUT ERROR DISPAYS ERROR MESSAGE ON OUTPUT
c234567
501   FORMAT(3I5)
601   FORMAT(" A= ",I5,"  B= ",I5,"  C= ",I5,"  AREA= ",F10.2,
     $"SQUARE UNITS")
602   FORMAT("NORMAL END")
603   FORMAT("INPUT ERROR OR ZERO VALUE ERROR")
      INTEGER A,B,C
 10   READ(*,501,END=50,ERR=90) A,B,C
      IF( A.EQ.0 .OR. B.EQ.0 .OR. C.EQ.0 ) GO TO 90
      S = (A + B + C) / 2.0
      AREA = SQRT( S * (S - A) * (S - B) * (S - C) )  
      WRITE(*,601) A,B,C,AREA
      GO TO 10
 50   WRITE(*,602)
      STOP
 90   WRITE(*,603)
      STOP
      END
